/*
 * generated by Xtext 2.30.0
 */
package org.misterwalter.lisp.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.misterwalter.lisp.LispRuntimeModule;
import org.misterwalter.lisp.LispStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class LispIdeSetup extends LispStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new LispRuntimeModule(), new LispIdeModule()));
	}
	
}
