/*
 * generated by Xtext 2.30.0
 */
package org.misterwalter.lisp.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class LispUiModule extends AbstractLispUiModule {

	public LispUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
