/*
 * generated by Xtext 2.30.0
 */
package org.misterwalter.lisp;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LispRuntimeModule extends AbstractLispRuntimeModule {
}
